### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by LogicalMooon** [LogicalMooon/BetterLogic#1]
- [ ] Find bugs 
- [ ] Fix bugs
- [ ] Make one that doesn't require opitifine
- [ ] Make it an actual resource pack, since this is just a test run to see how it will do
- [ ] Become motivated to make a remaster
- [ ] Make remaster
- [ ] Work
